apiVersion: apps/v1
kind: Deployment

metadata:
  name: webslab-app-dp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: webslab-app

spec:
  selector:
    matchLabels:
      app: webslab-app
  template:
    metadata:
      labels:
        app: webslab-app

    spec:
      containers:
        - name: webslab-app
          image: PLACEHOLDER_IMAGE
          imagePullPolicy: Always

          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: base_url

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: otel_exporter_otlp_endpoint

            - name: OTEL_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: otel_http_port

            - name: OTEL_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: otel_grpc_port

            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: api_port

            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: api_host

            - name: ISLAND_PORT
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: island_port

            - name: ISLAND_HOST
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: island_host

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: db_host

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: db_port

        - name: webslab-server
          image: docker.io/denoland/deno:distroless
          imagePullPolicy: Always

          # command: serve --unstable-otel --unstable-kv --unstable-cron -A --parallel --port 6000 dist/deno.ts
          command: ["serve"]
          args:
            [
              "--unstable-otel",
              "--unstable-kv",
              "--unstable-cron",
              "-A",
              "--parallel",
              "--port",
              "6000",
              "dist/deno.ts",
            ]

          env:
            - name: DENO_KV_STORAGE
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: deno_kv_storage

            - name: OTEL_DENO
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: otel_deno

            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: otel_service_name

            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: base_url

            - name: SITE_URL
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: site_url

            - name: PUBLIC_PROJECT_SPEC
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: public_project_spec

            - name: PUBLIC_PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: public_project_name

            - name: PUBLIC_DB_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: public_db_endpoint

            - name: SECRET_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webslab-secret-db
                  key: secret_db_username

            - name: SECRET_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webslab-secret-db
                  key: secret_db_password

            - name: PUBLIC_VAPID
              valuefrom:
                configmapkeyref:
                  name: webslab-cm
                  key: public_vapid

            - name: SECRET_VAPID
              valueFrom:
                secretKeyRef:
                  name: webslab-secret-vapid
                  key: secret_vapid

            - name: SECRET_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: webslab-secret-mail
                  key: secret_mail_port

            - name: SECRET_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: webslab-secret-mail
                  key: secret_mail_host

            - name: SECRET_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webslab-secret-mail
                  key: secret_mail_username

            - name: SECRET_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webslab-secret-mail
                  key: secret_mail_password

            - name: SECRET_BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: webslab-secret-better
                  key: secret_better_auth_secret

            - name: BETTER_AUTH_URL
              valuefrom:
                configmapkeyref:
                  name: webslab-cm
                  key: better_auth_url

          # volumeMounts:
          #   # - name: nfs-pvc
          #   - name: home-host
          #     mountPath: "/var/www/html/base"

        # - name: webslab-base-ff
        #   image: webslab/filefind:latest
        #   imagePullPolicy: "Always"
        #
        #   volumeMounts:
        #     #- name: nfs-pvc
        #     - name: home-host
        #       mountPath: "/app/resources/base"

      volumes:
        # - name: nfs-pvc
        #   persistentVolumeClaim:
        #     claimName: nfs-pvc

        - name: home-host
          hostPath:
            path: /home/webslab/base
            type: Directory
