apiVersion: apps/v1
kind: Deployment

metadata:
  name: webslab-app-dp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: webslab-app

spec:
  selector:
    matchLabels:
      app: webslab-app
  template:
    metadata:
      labels:
        app: webslab-app

    spec:
      containers:
        - name: webslab-app
          image: PLACEHOLDER_IMAGE
          imagePullPolicy: Always

          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: base_url

            - name: SITE_URL
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: site_url

            - name: PUBLIC_PROJECT_SPEC
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: public_project_spec

            - name: PUBLIC_PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: public_project_name

            - name: PUBLIC_DB_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: public_db_endpoint

            - name: DENO_KV_STORAGE
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: deno_kv_storage

            - name: BETTER_AUTH_URL
              valuefrom:
                configmapkeyref:
                  name: webslab-cm
                  key: better_auth_url

            - name: PUBLIC_TRACES
              valuefrom:
                configmapkeyref:
                  name: webslab-cm
                  key: public_traces

            - name: PUBLIC_LOGS
              valuefrom:
                configmapkeyref:
                  name: webslab-cm
                  key: public_logs

            - name: PUBLIC_VAPID
              valuefrom:
                configmapkeyref:
                  name: webslab-cm
                  key: public_vapid

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: webslab-cm
                  key: otel_exporter_otlp_endpoint

          # volumeMounts:
          #   # - name: nfs-pvc
          #   - name: home-host
          #     mountPath: "/var/www/html/base"

        # - name: webslab-base-ff
        #   image: webslab/filefind:latest
        #   imagePullPolicy: "Always"
        #
        #   volumeMounts:
        #     #- name: nfs-pvc
        #     - name: home-host
        #       mountPath: "/app/resources/base"

      volumes:
        # - name: nfs-pvc
        #   persistentVolumeClaim:
        #     claimName: nfs-pvc

        - name: home-host
          hostPath:
            path: /home/webslab/base
            type: Directory
