DEFINE USER OVERWRITE {{SECRET_DB_USERNAME}} ON DATABASE PASSWORD "{{SECRET_DB_PASSWORD}}"
  ROLES EDITOR DURATION FOR TOKEN 1d, FOR SESSION 12h;

DEFINE ACCESS OVERWRITE users ON DATABASE TYPE RECORD
  SIGNIN (SELECT * FROM user
    WHERE email = $email
      AND record::exists(<record> $sessionId)
      AND id = (SELECT VALUE userId FROM ONLY <record> $sessionId)
      AND session::ip() = (SELECT VALUE ipAddress FROM ONLY <record> $sessionId)
  )
  WITH JWT ALGORITHM HS512 KEY '{{SECRET_DB_KEY}}'
  WITH ISSUER KEY '{{SECRET_DB_KEY}}' DURATION FOR TOKEN 7d, FOR SESSION NONE;
