apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  creationTimestamp: null
  name: webslab-infra-secret-db-root
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"

spec:
  encryptedData:
    surreal_pass: AgA9uJKUWmdj9uwJoSHY327o0AMUjuS47KTmXWynyCTpbZfVa84ya5YfmwwC+YBXsBb7p2WI7dq4IAytsBP487JPkKrq/Y14ppaMZkSytPfuaUfzmaYZHJ6181ptWhAsz33rWhAmlivtvnb5jMLPcrUH0lRmn4/GuKLrz3bCmpz0MG+Th3v9xw/ngZ/dFyurxR1glsjAp3pc7ChBGwWOhKcHFLKNRioVIRcnY2IVLy175jWG2brVYIq8FT3Pox5Z1KnoT6DfWo+B6dQwsrDEIATiMQomby7xJdE+edhF3WTM+CwxTLqUVdPHOi4ICE7taGqAMg7XHKCFE4IsopK+3g1ZqIBc4vdi3COT9qVazNVvnSMimta2Jy58v8+3w9d9HC3Gan1gIMwb0xTAWwmXwqZmHoDsrTs1TtwTWAANtIn6Fd1xMPXYGe+YafeXQFM0/jiyzZddPD1H8+zbo+No9QSx4Dw71B6NdzX2vsW/F4LThnwkxyn8Z0J9i0GYPHLhmKXmoEWV72HJ84JbgUbWwKW+XaQ6qsh4X99x96v1inkN3I5j7PAEGeqJs6fTPXrAeXI1EP79hEw6cHkoPzV8q7PeysavscvKTMb3GCGuoN+kRZdoEqCNexbcKpfXm04C4r60ZL8ALTORtBynJAATJcG07hw+NtCCkkN8Qh63o1pikQ7+5AXjeBqzCP4LoQVCpnwG4snrZEG+hCVZ2ZhcOg==
    surreal_user: AgC8HUD/FItPB1y5QngkE7Y9Dx5KrU+BmOEZu3itYJ3xPqwc9xVpmuJbMN3H+XaZZXZkwxEnnUrLq+Nn/5feg+dGsQMJIhphsE1MIq+1Nl8ZBoXJFgnH3/V32WRhBJsZkQc2JugAzvC436lic+yhXPADEED2W2EylcAFa6iXJsQUn7ob5e6TabWa4P0twZBWtLzv/qVNTidy0GPZQ1FVJ4uIr6LT+PXyN1qexfJegpEJ29lRFo4W8DegBnUpscJRQnNyXu3txkPRtANOzasSqJELeojB0XOiLjEft/kOrrd1Cp6WIM+IOH3bwumRvUIdWXZLTzFr5dSej4jnF0oeam02WF5XMG8eeKkSYUTgXPjs3Bi3ayvVSnxbtLrjWqNx1FI2U5wKt6Fgqz5h6P/LEnZ2+QHVxvT/MfsSdrmG/YeRvKtnNYyiF0JXhwFFcHWTCS+6FmtcPaZEJ/KH5BNf8LfHPaPPMl7XNzIQ811/iIKyfPB19SGJcXrc6U+EQxxLBLvPuv1IZ7u45z2/xt87ZqVGOm6VjcZkIJRQ4DD59VX5zyKNDA//ieBrSCpmIv5COLnI3/iQ4n807TG89P8tPCg1l757d3h0vB36WrZN/y19KsNhxwB3wwnn2qyqP3LEUIbXlDTribz7Sq68INJiOdZ6ORO70yKVtpKjlCf0M0aUVkdFP5HS7I0/9VN7wQhmdpEHOaW4otsAmvWmtdEmdeoLeP4o+w==

  template:
    type: Opaque
    metadata:
      creationTimestamp: null
      name: webslab-infra-secret-db-root
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
