apiVersion: v1
kind: Service

metadata:
  name: webslab-infra-otel-svc

spec:
  type: ExternalName
  externalName: metrics-svc.metrics.svc.cluster.local

  ports:
    - port: 3000
      name: grafana
    - port: 4317
      name: otel-grpc
    - port: 4318
      name: otel-http
