apiVersion: v1
kind: ConfigMap

metadata:
  name: webslab-db-cm

data:
  surreal_log: info
  surreal_no_banner: "true"
  surreal_client_ip: X-Real-IP
  surreal_caps_allow_all: "true"
  surreal_telemetry_provider: otlp
  otel_exporter_otlp_endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}:4317 # TODO:
