apiVersion: v1
kind: PersistentVolume

metadata:
  name: webslab-db-pv

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany

  nfs:
    server: localhost
    path: /home/nfs

  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: webslab-db-pv

spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 2Gi
