services:
  web:
    image: nginx:alpine-otel

    environment:
      BASE_URL: ${BASE_URL}
      API_PORT: 3000
      API_HOST: 127.0.0.1
      ISLAND_PORT: 3000
      ISLAND_HOST: 127.0.0.1
      OTEL_HOST: 127.0.0.1
      OTEL_HTTP_PORT: 4318
      OTEL_GRPC_PORT: 4317

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.variables.conf:/etc/nginx/templates/10-variables.conf.template:ro
      # 🔽 prod:
      - ../dist/client:/var/www/html/${BASE_URL}:ro

    ports:
      - 8000:80 # nginx
      - 3000:3000 # server
      - 7000:7000 # grafana

  server:
    image: docker.io/denoland/deno:alpine
    command: deno serve -A --parallel --port 3000 dist/deno.ts

    working_dir: /app
    volumes:
      - ../deploy/deno.json:/app/deno.json:ro
      - ../deploy/deno.ts:/app/dist/deno.ts:ro
      - ../dist/server:/app/dist/server:ro

    network_mode: service:web

  otel:
    image: grafana/otel-lgtm:0.9.0
    environment:
      GF_SERVER_HTTP_PORT: "7000"

    network_mode: service:web
