services:
  web:
    image: nginx:alpine-otel

    environment:
      BASE_URL: ${BASE_URL}
      API_PORT: 6000
      API_HOST: 127.0.0.1
      ISLAND_PORT: 6000
      ISLAND_HOST: 127.0.0.1
      DB_HOST: 127.0.0.1
      DB_PORT: 8000
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_HTTP_PORT: 4318
      OTEL_GRPC_PORT: 4317

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.variables.conf:/etc/nginx/templates/10-variables.conf.template:ro
      - ./nginx.locations.conf:/etc/nginx/templates/20-locations.conf.template:ro
      # 🔽 prod:
      - ../dist/client:/var/www/html/${BASE_URL}:ro

    ports:
      - 8000:80 # nginx
      - 7000:7000 # grafana
      - 6000:6000 # server

  surrealdb:
    image: surrealdb/surrealdb:v2.3.0
    command:
      - start
      - memory
      - -A
      - --no-banner
      - --user=root
      - --pass=root

    environment:
      SURREAL_LOG: info # none, full, error, warn, info, debug, trace
      SURREAL_CLIENT_IP: X-Real-IP # Nginx real IP
      SURREAL_TELEMETRY_PROVIDER: otlp # otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}:4317

    network_mode: service:web

  server:
    image: docker.io/denoland/deno:distroless
    command: serve --unstable-otel -A --parallel --port 6000 dist/deno.ts

    environment:
      OTEL_DENO: true
      OTEL_SERVICE_NAME: ecliptic_server
      # OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}:4318
      BASE_URL: ${BASE_URL}
      SITE_URL: ${SITE_URL}
      PUBLIC_DB_ENDPOINT: http://127.0.0.1${BASE_URL}/db # NOTE: best way
      SECRET_DB_USERNAME: ${SECRET_DB_USERNAME}
      SECRET_DB_PASSWORD: ${SECRET_DB_PASSWORD}
      PUBLIC_VAPID: ${PUBLIC_VAPID}
      SECRET_VAPID: ${SECRET_VAPID}
      SECRET_MAIL_PORT: ${SECRET_MAIL_PORT}
      SECRET_MAIL_HOST: ${SECRET_MAIL_HOST}
      SECRET_MAIL_USERNAME: ${SECRET_MAIL_USERNAME}
      SECRET_MAIL_PASSWORD: ${SECRET_MAIL_PASSWORD}
      SECRET_BETTER_AUTH_SECRET: ${SECRET_BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}

    working_dir: /app
    volumes:
      - ../deploy/deno.json:/app/deno.json:ro
      - ../deploy/deno.ts:/app/dist/deno.ts:ro
      - ../dist/server:/app/dist/server:ro

    network_mode: service:web

  otel:
    image: grafana/otel-lgtm:0.9.0
    environment:
      GF_SERVER_HTTP_PORT: "7000"

    network_mode: service:web
