FROM nginx:alpine-otel

# nginx config
COPY deploy/nginx.conf /etc/nginx/nginx.conf
COPY deploy/nginx.default.conf /etc/nginx/conf.d/default.conf
COPY deploy/nginx.variables.conf /etc/nginx/templates/10-variables.conf.template

# web app
COPY /dist /var/www/html
