services:
  web:
    image: nginx:alpine-otel
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.variables.conf:/etc/nginx/templates/10-variables.conf.template:ro
      # 🔽 prod:
      - ../dist:/var/www/html

    environment:
      OTEL_HOST: 127.0.0.1
      OTEL_HTTP_PORT: 4318
      OTEL_GRPC_PORT: 4317

    ports:
      - 8000:80 # nginx
      - 7000:7000 # grafana

  otel:
    image: grafana/otel-lgtm:0.9.0
    environment:
      GF_SERVER_HTTP_PORT: "7000"

    network_mode: service:web
