apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: webslab-app-ing
  annotations:
    spec.ingressClassName: traefic
    cert-manager.io/issuer: webslab-infra-issuer
    traefic.ingress.kubernetes.io/router.tls: "true"

spec:
  tls:
    - hosts:
        - ipsitec.es
      secretName: webslab-app-base-ing

  rules:
    - host: ipsitec.es
      http:
        paths:
          - path: /ecliptic
            pathType: Prefix
            backend:
              service:
                name: webslab-app-svc
                port:
                  number: 80
