apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ./sealed-better.yaml
  - ./sealed-db.yaml
  - ./sealed-mail.yaml
  - ./sealed-vapid.yaml
  - ./ingress.yaml

namespace: webslab-foo
nameSuffix: -prod

commonLabels:
  app: webslab-app-prod
  environment: prod

images:
  - name: PLACEHOLDER_IMAGE
    newName: docker.io/kennycallado/borrar # TODO: update
    newTag: latest

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: ./deployment.yaml
    target:
      kind: Deployment
      name: webslab-app-dp

replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name

    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - metadata.annotations.[traefik.ingress.kubernetes.io/router.middlewares]
        options:
          delimiter: "-"
