name: Build Images

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_app:
    name: Build app
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      SITE_URL: ${{ vars.SITE_URL }}
      BETTER_AUTH_URL: ${{ vars.BETTER_AUTH_URL }}
      PUBLIC_PROJECT_SPEC: ${{ vars.PUBLIC_PROJECT_SPEC }}
      PUBLIC_PROJECT_NAME: ${{ vars.PUBLIC_PROJECT_NAME }}
      PUBLIC_TRACES: ${{ vars.PUBLIC_TRACES }}
      PUBLIC_LOGS: ${{ vars.PUBLIC_LOGS }}
      PUBLIC_VAPID: ${{ vars.PUBLIC_VAPID }}
    permissions:
      actions: write
      contents: read
      packages: write

    steps:
      - name: Env test
        run: |
          echo $BASE_URL
          echo $SITE_URL
          echo $BETTER_AUTH_URL
          echo $PUBLIC_PROJECT_SPEC
          echo $PUBLIC_PROJECT_NAME
          echo $PUBLIC_TRACES
          echo $PUBLIC_LOGS
          echo $PUBLIC_VAPID

      - name: Checkout
        uses: actions/checkout@v4

      - name: Preapre bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build app
        run: bun run build:prod

      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: my-artifact
          path: dist/
          if-no-files-found: error
          retention-days: 1

  build_ghcr:
    name: Build ghcr images
    needs: [build_app]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: dist/

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: deploy/Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build_hub:
    name: Build docker hub images
    needs: [build_app]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: dist/

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: deploy/Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
